# version: '2'
# services:
#     zookeeper:
#         image: wurstmeister/zookeeper
#         ports:
#           - 2181:2181
#     kafka:
#         image: wurstmeister/kafka
#         environment:
#             KAFKA_ADVERTISED_HOST_NAME: 192.168.1.106
#             KAFKA_ADVERTISED_PORT: 9092
#             KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#             KAFKA_CREATE_TOPICS: "topic-jhipster:1:1"
#         ports:
#             - 9092:9092
version: '2'
services:
  message-kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.106
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.106:2181,192.168.1.108:2181
      # KAFKA_CREATE_TOPICS: "192.168.1.106"
